# NekoAlert 配置文件
# 间隔时间，单位秒
time: 60

# 消息列表，支持颜色代码和链接
# 你可以添加任意数量的行，例如 line3, line4 等
messages:
  line1:
    - "&a[公告] &f欢迎来到服务器！"
    - "&b[提示] &f请遵守服务器规则。"
    - "&c[警告] &f不要破坏他人建筑。"
    - "&e[活动] &f即将举办建筑比赛，敬请期待！"

  line2:
    - "&d[社交] &f加入我们的Discord: &nhttps://discord.gg/example"
    - "&6[商店] &f访问我们的商店: &nhttps://store.example.com"
    - "&9[活动] &f每周六晚上8点有PvP比赛！"
    - "&c[提醒] &f记得备份你的建筑作品。"
    - "&a[公告] &f欢迎来到服务器！"